name: portfolio
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  stacked: ^3.4.1+1
  stacked_hooks: ^0.2.3
  animated_text_kit: ^4.2.2
  url_launcher: ^6.3.0
  flutter_staggered_grid_view: ^0.7.0
  code_text_field: ^1.1.0
  video_player: ^2.9.1
  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  path_provider: ^2.1.3
  particles_flutter: ^0.1.4
  animated_background: ^2.0.0
  animated_gradient: ^0.0.3
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/me/
    - assets/icons/
    - assets/display/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/nunito/Nunito-Regular.ttf
        - asset: fonts/nunito/Nunito-Italic.ttf
          style: italic
    - family: SourceCode
      fonts:
        - asset: fonts/source-code/SourceCodePro-Regular.ttf
    - family: FiraCode
      fonts:
        - asset: fonts/fira-code/FiraCode.ttf